#!/bin/bash
#
# Title:      PSAutomate
# Based On:   PGBlitz (Reference Title File)
# Original Author(s):  Admin9705 - Deiteq
# PSAutomate Auther: fattylewis
# URL:        https://psautomate.io - http://github.psautomate.io
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: "Creating Folder - /psa/{{drive}}"
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
      with_items:
        - "/psa/{{drive}}"

    - name: Register Agent
      shell: 'cat /psa/var/uagent'
      register: uagent

    - name: "Install - Service {{drive}}"
      template:
        src: "/psa/psaclone/mounts/crypt.service"
        dest: "/etc/systemd/system/{{drive}}.service"
        force: yes
      ignore_errors: yes

    - name: "Reload Service - {{drive}}"
      systemd:
        daemon_reload: yes
        enabled: yes
        state: reloaded
        name: "{{drive}}"
